export type Category = {
  id: string;
  name: string;
  slug: string;
  description: string;
  image_url: string;
  created_at: string;
};

export type Product = {
  id: string;
  name: string;
  slug: string;
  category_id: string;
  description: string;
  specs: Record<string, string>;
  price_label: string;
  images: string[];
  featured: boolean;
  whatsapp_message?: string;
  created_at: string;
};

const baseUrl = import.meta.env.BASE_URL.replace(/\/$/, '');
const asset = (path: string) => `${baseUrl}${path}`;

export const mockCategories: Category[] = [
  {
    id: 'c-1',
    name: 'Kamp Çadırları',
    slug: 'cadirlar',
    description: 'Karadeniz rüzgarlarına dayanıklı, 4 mevsimlik kamp çadırları ve barınma ekipmanları.',
    image_url: asset('/mock/category-cadir.jpg'),
    created_at: new Date().toISOString(),
  },
  {
    id: 'c-2',
    name: 'Olta & Balık Malzemeleri',
    slug: 'olta-ve-makine',
    description: 'Kıyıdan veya tekneden avlanmak için en kaliteli olta kamışları, balık makineleri ve balık malzemeleri.',
    image_url: asset('/mock/category-olta.jpg'),
    created_at: new Date().toISOString(),
  },
  {
    id: 'c-3',
    name: 'Kamp Ekipmanları',
    slug: 'kamp-aksesuarlari',
    description: 'Kamp ocağı, kamp masası, sırt çantası ve daha fazlası — doğada ev konforu için kamp ekipmanları.',
    image_url: asset('/mock/category-aksesuar.jpg'),
    created_at: new Date().toISOString(),
  },
  {
    id: 'c-4',
    name: 'Aydınlatma',
    slug: 'aydinlatma',
    description: 'Gece avları ve kamp geceleri için şarjlı fenerler, kafa lambaları ve kamp aydınlatma sistemleri.',
    image_url: asset('/mock/category-aydinlatma.jpg'),
    created_at: new Date().toISOString(),
  },
  {
    id: 'c-5',
    name: 'Termos & Soğutucu',
    slug: 'termos-ve-sogutucu',
    description: 'Uzun kamp geceleri ve balık avı için içecekleri sıcak, yiyecekleri soğuk tutan premium termos ve soğutucu seçenekleri.',
    image_url: asset('/mock/product-5.jpg'),
    created_at: new Date().toISOString(),
  },
  {
    id: 'c-6',
    name: 'Olta Aksesuarları',
    slug: 'olta-aksesuarlari',
    description: 'Sahte yem, iğne, misina, olta takımı ve balık avı aksesuarları — her türlü av için doğru ekipman.',
    image_url: asset('/mock/product-4.jpg'),
    created_at: new Date().toISOString(),
  },
  {
    id: 'c-7',
    name: 'Outdoor & Trekking',
    slug: 'outdoor-aksesuarlari',
    description: 'Doğa yürüyüşü, trekking ve outdoor maceraları için kıyafet, çanta, bıçak ve survival ekipmanları.',
    image_url: asset('/mock/product-6.jpg'),
    created_at: new Date().toISOString(),
  },
];

export const mockProducts: Product[] = [
  /* ── c-1: Kamp Çadırları ── */
  {
    id: 'p-1',
    name: 'Alpinist Pro 4 Mevsim Kamp Çadırı',
    slug: 'alpinist-pro-4-mevsim-kamp-cadiri',
    category_id: 'c-1',
    description: 'Yoğun yağış ve şiddetli rüzgara karşı ekstra güçlendirilmiş alüminyum poller. Kaçkar Dağları\'nda defalarca test edilmiş, su geçirmez 3000mm kolon direncine sahip profesyonel çadır.',
    specs: {
      'Kapasite': '3 Kişilik',
      'Ağırlık': '3.2 kg',
      'Su Geçirmezlik': '3000mm',
      'Pol Malzemesi': '7001 Alüminyum',
    },
    price_label: '₺4.250',
    images: [asset('/mock/product-1.jpg'), asset('/mock/category-cadir.jpg')],
    featured: true,
    whatsapp_message: 'Alpinist Pro 4 Mevsim Kamp Çadırı hakkında bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-2',
    name: 'Kuzey Yıldızı Uyku Tulumu (-15°C)',
    slug: 'kuzey-yildizi-uyku-tulumu',
    category_id: 'c-1',
    description: 'Eksi derecelerde bile sıcacık bir uyku sunan, hafif ve kompakt uyku tulumu. Sentetik dolgusu sayesinde nemli Karadeniz havasında bile yalıtım özelliğini korur.',
    specs: {
      'Konfor Derecesi': '-5°C',
      'Ekstrem Derece': '-15°C',
      'Ağırlık': '1.4 kg',
      'Dolgu': 'Hollowfibre Sentetik',
    },
    price_label: '₺1.850',
    images: [asset('/mock/product-1.jpg')],
    featured: false,
    whatsapp_message: 'Kuzey Yıldızı Uyku Tulumu için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-13',
    name: 'Trailblazer 2 Kişilik Trekking Çadırı',
    slug: 'trailblazer-2-kisilik-trekking-cadiri',
    category_id: 'c-1',
    description: 'Tek çubuklu kurulum sistemi sayesinde tek kişi tarafından 5 dakikada kurulabilen hafif ve kompakt trekking çadırı.',
    specs: {
      'Kapasite': '2 Kişilik',
      'Ağırlık': '2.1 kg',
      'Su Geçirmezlik': '2000mm',
      'Kurulum': 'Tek Çubuklu',
    },
    price_label: '₺2.900',
    images: [asset('/mock/category-cadir.jpg')],
    featured: false,
    whatsapp_message: 'Trailblazer 2 Kişilik Çadır için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-14',
    name: 'Kamp Paspas Seti — Eva Köpük 3\'lü',
    slug: 'kamp-paspas-seti-eva-kopuk',
    category_id: 'c-1',
    description: 'Zemin soğukluğunu ve nem transfer eden yüzeyleri engelleyen 3 cm kalınlığında Eva köpük zemin paspası. Rulo yapılarak çantaya bağlanır.',
    specs: {
      'Boyut': '185x58 cm',
      'Kalınlık': '3 cm',
      'Malzeme': 'Eva Köpük',
      'Paket': '3 Adet',
    },
    price_label: '₺480',
    images: [asset('/mock/product-1.jpg')],
    featured: false,
    whatsapp_message: 'Eva köpük paspas seti için bilgi istiyorum.',
    created_at: new Date().toISOString(),
  },

  /* ── c-2: Olta & Balık Malzemeleri ── */
  {
    id: 'p-3',
    name: 'Fırtına Karbon Spin Olta Kamışı 270cm',
    slug: 'firtina-karbon-spin-olta-kamisi-270cm',
    category_id: 'c-2',
    description: 'Levrek ve lüfer avcıları için özel olarak tasarlanmış, at-çek avlarında yorulmadan saatlerce kullanabileceğiniz yüksek modüllü karbon kamış.',
    specs: {
      'Boy': '270 cm',
      'Atar': '15-40 gr',
      'Ağırlık': '165 gr',
      'Parça Sayısı': '2',
    },
    price_label: '₺2.100',
    images: [asset('/mock/product-3.jpg')],
    featured: true,
    whatsapp_message: 'Fırtına Karbon Olta Kamışı için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-4',
    name: 'Karadeniz Surf Olta Makinesi 6000',
    slug: 'karadeniz-surf-olta-makinesi-6000',
    category_id: 'c-2',
    description: 'Tuzlu suya ekstra dayanıklı paslanmaz çelik bilyalar. Kıyıdan uzak atışlar için tasarlanmış sığ kafa yapısı ve güçlü kalama sistemi.',
    specs: {
      'Bilya Sayısı': '5+1',
      'Devir': '4.6:1',
      'Kalama Gücü': '12 kg',
      'Ağırlık': '420 gr',
    },
    price_label: 'Fiyat için sorunuz',
    images: [asset('/mock/product-3.jpg')],
    featured: false,
    whatsapp_message: 'Karadeniz Surf Makinesi 6000 için fiyat almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-15',
    name: 'Levrek Pro Jigging Olta Seti (Komple)',
    slug: 'levrek-pro-jigging-olta-seti',
    category_id: 'c-2',
    description: 'Kamış + makine + misina kombinasyonu olarak hazır paket. Karadeniz levrek avcılığı için optimize edilmiş, hemen kullanıma hazır komple olta seti.',
    specs: {
      'Kamış': '210cm Carbon Jigging',
      'Makine': '3000 Spinning',
      'Misina': '0.30mm 150m',
      'Atar': '10-30 gr',
    },
    price_label: '₺1.750',
    images: [asset('/mock/category-olta.jpg')],
    featured: true,
    whatsapp_message: 'Levrek Pro Jigging Seti için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-16',
    name: 'Hamsi Teknesi Olta Takımı 12\'li',
    slug: 'hamsi-teknesi-olta-takimi-12li',
    category_id: 'c-2',
    description: 'Karadeniz hamsi mevsiminde tekneden balık avlamak için özel üretilmiş, 12 iğneli parlak taklitli hamsi oltası.',
    specs: {
      'İğne Sayısı': '12 Adet',
      'Tip': 'Hamsi Oltası',
      'Misina': '0.40mm',
      'Kurşun': '100gr',
    },
    price_label: '₺180',
    images: [asset('/mock/product-3.jpg')],
    featured: false,
    whatsapp_message: 'Hamsi Teknesi Olta Takımı için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },

  /* ── c-3: Kamp Ekipmanları ── */
  {
    id: 'p-6',
    name: 'Odun Ateşi Portatif Kamp Ocağı',
    slug: 'odun-atesi-portatif-kamp-ocagi',
    category_id: 'c-3',
    description: 'Küçük dallar ve kozalaklarla çayınızı anında demleyin. Katlanabilir çelik gövdesi ile çantada hiç yer kaplamaz.',
    specs: {
      'Malzeme': 'Paslanmaz Çelik',
      'Kurulu Boyut': '15x15x20 cm',
      'Katlı Boyut': '15x15x2 cm',
      'Ağırlık': '450 gr',
    },
    price_label: '₺380',
    images: [asset('/mock/product-2.jpg')],
    featured: true,
    whatsapp_message: 'Portatif Kamp Ocağı için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-8',
    name: 'Zirve Katlanır Kamp Masası',
    slug: 'zirve-katlanir-kamp-masasi',
    category_id: 'c-3',
    description: 'Alüminyum iskeleti ve kumaş tablası sayesinde sadece 1 kg ağırlığında. İki kişilik kamp yemekleri için ideal kompakt çözüm.',
    specs: {
      'Taşıma Kapasitesi': '25 kg',
      'Yüzey Malzemesi': '600D Oxford Kumaş',
      'Kurulu Boyut': '56x42x40 cm',
      'Ağırlık': '1.1 kg',
    },
    price_label: '₺650',
    images: [asset('/mock/category-aksesuar.jpg')],
    featured: false,
    whatsapp_message: 'Katlanır Kamp Masası için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-11',
    name: 'Orman Gezgini 45L Sırt Çantası',
    slug: 'orman-gezgini-45l-sirt-cantasi',
    category_id: 'c-3',
    description: 'Günübirlik veya hafta sonu yürüyüşleri için ideal. Sırtı terletmeyen air-mesh teknolojisi ve entegre yağmurluk.',
    specs: {
      'Hacim': '45 Litre',
      'Kumaş': 'Su İtici Naylon',
      'Sırt Sistemi': 'Ergonomik Air-Mesh',
      'Ekstra': 'Dahili Yağmurluk',
    },
    price_label: '₺1.450',
    images: [asset('/mock/product-6.jpg')],
    featured: false,
    whatsapp_message: 'Orman Gezgini Sırt Çantası için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-12',
    name: 'Aygaz Kamp Çaydanlığı',
    slug: 'aygaz-kamp-caydanligi',
    category_id: 'c-3',
    description: 'Sertleştirilmiş alüminyumdan üretilmiş, doğada çay keyfinden vazgeçemeyenler için ultra hafif demlik. Hızlı ısınır, yakıt tasarrufu sağlar.',
    specs: {
      'Kapasite': '1.2 Litre',
      'Malzeme': 'Sert Eloksallı Alüminyum',
      'Ağırlık': '210 gr',
      'Sap': 'Isıya Dayanıklı Silikon',
    },
    price_label: '₺420',
    images: [asset('/mock/product-2.jpg')],
    featured: false,
    whatsapp_message: 'Kamp Çaydanlığı için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },

  /* ── c-4: Aydınlatma ── */
  {
    id: 'p-9',
    name: 'Gölge Şarjlı Kamp Feneri',
    slug: 'golge-sarjli-kamp-feneri',
    category_id: 'c-4',
    description: 'Hem şarj edilebilir hem de powerbank olarak kullanılabilir. Çadır içini 360 derece aydınlatan sıcak sarı ışık modu ile kamp gecelerinize eşlik eder.',
    specs: {
      'Işık Gücü': '400 Lümen',
      'Pil Kapasitesi': '5000 mAh',
      'Çalışma Süresi': '12 Saat (Sürekli)',
      'Su Dayanımı': 'IPX4',
    },
    price_label: '₺850',
    images: [asset('/mock/category-aydinlatma.jpg')],
    featured: true,
    whatsapp_message: 'Şarjlı Kamp Feneri için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-10',
    name: 'Avcı Pro Kafa Lambası',
    slug: 'avci-pro-kafa-lambasi',
    category_id: 'c-4',
    description: 'Gece avları ve doğa yürüyüşleri için hareket sensörlü aç/kapa özelliği. Kırmızı ışık modu ile gece görüşünüzü bozmaz.',
    specs: {
      'Işık Gücü': '250 Lümen',
      'Mesafe': '100 Metre',
      'Ağırlık': '75 gr',
      'Modlar': 'Beyaz / Kırmızı / Çakar',
    },
    price_label: '₺550',
    images: [asset('/mock/category-aydinlatma.jpg')],
    featured: false,
    whatsapp_message: 'Avcı Pro Kafa Lambası için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-17',
    name: 'SolarPower Taşınabilir Güneş Paneli',
    slug: 'solarpower-tasinaril-gunes-paneli',
    category_id: 'c-4',
    description: 'Kamp ve av gecelerinde telefonunuzu ve kafa lambanızı şarj etmek için kompakt, katlanabilir güneş paneli. USB-A ve USB-C çıkışı.',
    specs: {
      'Güç': '20W',
      'Çıkış': 'USB-A + USB-C',
      'Ağırlık': '580 gr',
      'Katlanmış Boyut': '28x16x2 cm',
    },
    price_label: '₺1.200',
    images: [asset('/mock/category-aydinlatma.jpg')],
    featured: false,
    whatsapp_message: 'SolarPower Güneş Paneli için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },

  /* ── c-5: Termos & Soğutucu ── */
  {
    id: 'p-7',
    name: 'Buzul 30L Tekne & Kamp Soğutucusu',
    slug: 'buzul-30l-kamp-termosu',
    category_id: 'c-5',
    description: '3 gün boyunca buzları çözülmeden muhafaza eden, zorlu doğa koşullarına dayanıklı ekstra yalıtımlı poliüretan gövde.',
    specs: {
      'Kapasite': '30 Litre',
      'Yalıtım Süresi': '72 Saat',
      'Dış Malzeme': 'Yüksek Yoğunluklu PE',
      'Boş Ağırlık': '3.5 kg',
    },
    price_label: '₺1.950',
    images: [asset('/mock/product-5.jpg')],
    featured: true,
    whatsapp_message: 'Buzul 30L Soğutucu için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-18',
    name: 'Titan Vakumlu Kamp Termosu 1L',
    slug: 'titan-vakumlu-kamp-termosu-1l',
    category_id: 'c-5',
    description: 'Çift cidarlı vakum yalıtımı ile 24 saat sıcak, 48 saat soğuk içecek muhafazası. Paslanmaz çelik iç gövde.',
    specs: {
      'Kapasite': '1 Litre',
      'Sıcak Tutma': '24 Saat',
      'Soğuk Tutma': '48 Saat',
      'Malzeme': '304 Paslanmaz Çelik',
    },
    price_label: '₺680',
    images: [asset('/mock/product-5.jpg')],
    featured: false,
    whatsapp_message: 'Titan Vakumlu Termos için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-19',
    name: 'IcePack 12L Piknik & Balık Çantası',
    slug: 'icepack-12l-piknik-balik-cantasi',
    category_id: 'c-5',
    description: 'Hem yiyecek saklama hem de avlanan balıkları taze tutmak için tasarlanmış, 6 saat soğutucu kapasiteli termal çanta.',
    specs: {
      'Kapasite': '12 Litre',
      'Soğutucu Süre': '6 Saat',
      'Malzeme': 'Isı Yalıtımlı Astar',
      'Kapak': 'Su Geçirmez Fermuar',
    },
    price_label: '₺320',
    images: [asset('/mock/product-5.jpg')],
    featured: false,
    whatsapp_message: 'IcePack Balık Çantası için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },

  /* ── c-6: Olta Aksesuarları ── */
  {
    id: 'p-5',
    name: 'Derin Su Sahte Yem Seti (5 Parça)',
    slug: 'derin-su-sahte-yem-seti',
    category_id: 'c-6',
    description: 'Gece avlarında yüksek verim sağlayan fosforlu gövdeye sahip, su içinde gerçekçi aksiyon gösteren 5 farklı renkte sahte yem seti.',
    specs: {
      'Boy': '11 cm',
      'Ağırlık': '15 gr',
      'Aksiyon': 'Dalan (Sinking)',
      'İğne': 'VMC Paslanmaz',
    },
    price_label: '₺450',
    images: [asset('/mock/product-4.jpg')],
    featured: false,
    whatsapp_message: 'Sahte Yem Seti için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-20',
    name: 'Karadeniz Hamsi Yemi Seti (10 Parça)',
    slug: 'karadeniz-hamsi-yemi-seti-10-parca',
    category_id: 'c-6',
    description: 'Hamsi, istavrit ve sardalya avcılığı için özel parlaklık ve boyutta taklit yem seti. Tekne avcılığında kullanıma uygundur.',
    specs: {
      'İçerik': '10 Adet Taklit Yem',
      'Boy': '4-6 cm',
      'Tip': 'Parlak Metal Kaşık',
      'Uygun Av': 'Hamsi, İstavrit',
    },
    price_label: '₺220',
    images: [asset('/mock/product-4.jpg')],
    featured: false,
    whatsapp_message: 'Hamsi Yemi Seti için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-21',
    name: 'Fluoro Carbon Misina 0.25-0.40mm (300m)',
    slug: 'fluoro-carbon-misina-300m',
    category_id: 'c-6',
    description: 'Tuzlu suda yüksek aşınma direnci ve düşük esneme oranı sunan fluoro carbon misina. Kıyı ve tekne avcılığına uygundur.',
    specs: {
      'Boy': '300 Metre',
      'Çap Seçeneği': '0.25 / 0.30 / 0.35 / 0.40mm',
      'Kırılma Gücü': '8-16 kg',
      'Malzeme': 'Fluoro Carbon',
    },
    price_label: '₺180',
    images: [asset('/mock/product-4.jpg')],
    featured: false,
    whatsapp_message: 'Fluoro Carbon Misina için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-22',
    name: 'Balık İğnesi Seti — 8 Farklı Beden (200 Adet)',
    slug: 'balik-ignesi-seti-200-adet',
    category_id: 'c-6',
    description: 'En popüler 8 farklı beden iğneyi bir arada sunan pratik plastik kutu içinde organize balık iğnesi seti.',
    specs: {
      'İçerik': '200 Adet',
      'Beden': '2-12 Numara',
      'Malzeme': 'Karbon Çelik + Nikel Kaplama',
      'Tip': 'Halkalı ve Halkasız',
    },
    price_label: '₺135',
    images: [asset('/mock/product-4.jpg')],
    featured: false,
    whatsapp_message: 'Balık İğnesi Seti için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },

  /* ── c-7: Outdoor & Trekking ── */
  {
    id: 'p-23',
    name: 'Summit Trekking Bıçağı — G10 Saplı',
    slug: 'summit-trekking-bicagi-g10-sapli',
    category_id: 'c-7',
    description: 'Full-tang çelik gövde ve su geçirmez G10 kompozit sap. Kamp, balık temizleme ve survival kullanıma uygun çok amaçlı trekking bıçağı.',
    specs: {
      'Çelik': '440C Paslanmaz',
      'Sap': 'G10 Kompozit',
      'Toplam Uzunluk': '22 cm',
      'Ağırlık': '180 gr',
    },
    price_label: '₺750',
    images: [asset('/mock/product-6.jpg')],
    featured: true,
    whatsapp_message: 'Summit Trekking Bıçağı için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-24',
    name: 'MultiTool Pro — 18 Fonksiyonlu Çakı',
    slug: 'multitool-pro-18-fonksiyonlu-caki',
    category_id: 'c-7',
    description: 'Pense, bıçak, tornavida, makas ve daha fazlasını tek bir alette toplayan paslanmaz çelik multi-tool. Outdoor ve kamp için vazgeçilmez.',
    specs: {
      'Fonksiyon': '18 Adet',
      'Malzeme': '420 Paslanmaz Çelik',
      'Ağırlık': '220 gr',
      'Kılıf': 'Deri Kılıf Dahil',
    },
    price_label: '₺420',
    images: [asset('/mock/product-6.jpg')],
    featured: false,
    whatsapp_message: 'MultiTool Pro için bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-25',
    name: 'Survival Kit — Acil Durum Seti 12 Parça',
    slug: 'survival-kit-acil-durum-seti',
    category_id: 'c-7',
    description: 'Dağ, orman ve kıyı maceralarında hayatta kalma ve ilk yardım için 12 zorunlu eleman. Su geçirmez çanta içinde organize.',
    specs: {
      'İçerik': '12 Parça',
      'Paket': 'Su Geçirmez Poşet',
      'Boyut': '15x10x5 cm',
      'Ağırlık': '320 gr',
    },
    price_label: '₺380',
    images: [asset('/mock/product-6.jpg')],
    featured: false,
    whatsapp_message: 'Survival Kit hakkında bilgi almak istiyorum.',
    created_at: new Date().toISOString(),
  },
];
