// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/saricam-meridian/CinematicEditorial.tsx": () => import("../components/mockups/saricam-meridian/CinematicEditorial.tsx"),
  "./components/mockups/saricam-meridian/MagazineAsymmetric.tsx": () => import("../components/mockups/saricam-meridian/MagazineAsymmetric.tsx"),
  "./components/mockups/saricam-meridian/MoodyAtmosphere.tsx": () => import("../components/mockups/saricam-meridian/MoodyAtmosphere.tsx")
};
